model:
  q : [ [-0.3,    0.3],
        [0.3,     -0.3] ]
  birth_rates : [1.15, 2.2]
  death_rates : [0.5, 0.5]
  burst_rate : 0.0
  burst_probs : [0.1, 0.8]
  burst_furcation_poisson_means : [0.6, 0.6]
  burst_furcation_poisson_shifts : [2, 2]
  only_bifurcate : False

settings:
  prune_extinct_leaves: True
  keep_extinct_trees: False
  max_leaves_strict: True
  stopping_conditions:
    max_extant_leaves : 368
