model:
  q : [ [-1.0,    1.0],
        [1.0,     -1.0] ]
  birth_rates : [1.0, 1.0]
  death_rates : [0.5, 0.5]
  burst_rate : 0.5
  burst_probs : [0.1, 0.6]
  burst_furcation_poisson_means : [1.0, 2.0]
  burst_furcation_poisson_shifts : [2, 2]
  only_bifurcate : False

settings:
  prune_extinct_leaves: True
  keep_extinct_trees: False
  stopping_conditions:
    max_extant_leaves : 50
